### ISSUE TITLE
Input/Output Clarification

### ISSUE THREAD

**Issue by CrazyPyroEagle** [animemelang/compiler#1]
What is the input format and the output format for this compiler?

Am I correct in guessing that the input format is a [web components](https://github.com/animemelang/web-components) file, and the output is a program binary?

**Comment by bucket3432** [comment]
I was thinking it would take in as input a script-like representation and output an image, but taking in the XML and outputting an executable sounds like a much better idea. I vote for that.

**Comment by bucket3432** [comment]
Should our output instead be a C program? That way, we don't have to deal with having multiple architectures.

**Comment by AlexandreTunstall** [comment]
I suggest instead outputting LLVM, which was designed to be used as a compiler backend.

**Comment by CrazyPyroEagle** [comment]
I suggest instead outputting LLVM, which was designed as a compiler backend, and should give more control over the output than C.

**Comment by bucket3432** [comment]
LLVM looks like it was made for this, so yes, let's go with that. In that case, let's proceed with Animeme XML as input and LLVM as output.

If we want a more traditional scripting language, as input, we can always write a compiler to go from that to XML later.

**Comment by CrazyPyroEagle** [comment]
The traditional scripting language would just be an alternative front-end. Later compiler stages could be reused if the XML and script are parsed into the same AST.

Closing due to a conclusive discussion, please reopen if you believe there is more to discuss on this topic.
